[build]
builder = "NIXPACKS"  # or "DOCKERFILE" if you are using a custom Dockerfile

[build.nixpacks]
language = "python"
buildCommand = "pip install -r requirements.txt"

[start]
cmd = "python app.py"
